In [1]:
import pandas as pd
import requests

In [3]:
response=requests.get('https://api.themoviedb.org/3/tv/top_rated?api_key=7ff9928e01325480ca86fddb66fa93d7')
response

In [4]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/7BzmK4MWc0cj4hCxwWURt6TS6UR.jpg',
   'genre_ids': [16, 10765, 10759, 35],
   'id': 131378,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Adventure Time: Fionna & Cake',
   'overview': 'Fionna and Cake – with the help of the former Ice King, Simon Petrikov - embark on a multiverse-hopping adventure and journey of self-discovery. All the while a powerful new antagonist determined to track them down and erase them from existence, lurks in the shadows.',
   'popularity': 35.818,
   'poster_path': '/fi1b6U1kp73xheECzqwzMn8u3mX.jpg',
   'first_air_date': '2023-08-31',
   'name': 'Adventure Time: Fionna & Cake',
   'vote_average': 8.995,
   'vote_count': 203},
  {'adult': False,
   'backdrop_path': '/gc8PfyTqzqltKPW3X0cIVUGmagz.jpg',
   'genre_ids': [18, 80],
   'id': 1396,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Breaking Bad',
   'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
   'popularity': 737.144,
   'poster_path': '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
   'first_air_date': '2008-01-20',
   'name': 'Breaking Bad',
   'vote_average': 8.9,
   'vote_count': 14963},
  {'adult': False,
   'backdrop_path': '/j67Wi1mzPxPVVybjmaIsvzsqFDH.jpg',
   'genre_ids': [16, 10759, 35, 10765],
   'id': 240411,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': 'ダンダダン',
   'overview': 'In a bet to prove whether ghosts or aliens exist, two high schoolers face terrifying paranormal threats, gain superpowers and maybe even fall in love?!',
   'popularity': 189.932,
   'poster_path': '/6qfZAOEUFIrbUH3JvePclx1nXzz.jpg',
   'first_air_date': '2024-10-04',
   'name': 'Dan Da Dan',
   'vote_average': 8.8,
   'vote_count': 386},
  {'adult': False,
   'backdrop_path': '/tuCU2yVRM2iZxFkpqlPUyvd6tSu.jpg',
   'genre_ids': [16, 35, 10765],
   'id': 94954,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Hazbin Hotel',
   'overview': "In attempt to find a non-violent alternative for reducing Hell's overpopulation, the daughter of Lucifer opens a rehabilitation hotel that offers a group of misfit demons a chance at redemption.",
   'popularity': 110.633,
   'poster_path': '/rXojaQcxVUubPLSrFV8PD4xdjrs.jpg',
   'first_air_date': '2024-01-18',
   'name': 'Hazbin Hotel',
   'vote_average': 8.8,
   'vote_count': 1214},
  {'adult': False,
   'backdrop_path': '/sYXLeu5usz6yEz0k00FYvtEdodD.jpg',
   'genre_ids': [16, 10765, 18, 10759],
   'id': 94605,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Arcane',
   'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
   'popularity': 260.242,
   'poster_path': '/abf8tHznhSvl9BAElD2cQeRr7do.jpg',
   'first_air_date': '2021-11-06',
   'name': 'Arcane',
   'vote_average': 8.8,
   'vote_count': 4846},
  {'adult': False,
   'backdrop_path': '/96RT2A47UdzWlUfvIERFyBsLhL2.jpg',
   'genre_ids': [16, 10759, 10765, 18],
   'id': 209867,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '葬送のフリーレン',
   'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude. Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
   'popularity': 160.004,
   'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
   'first_air_date': '2023-09-29',
   'name': "Frieren: Beyond Journey's End",
   'vote_average': 8.776,
   'vote_count': 378},
  {'adult': False,
   'backdrop_path': '/kU98MbVVgi72wzceyrEbClZmMFe.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 246,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Avatar: The Last Airbender',
   'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
   'popularity': 73.219,
   'poster_path': '/v2vn1coUMPKw0GI1KGC5J4IXtqp.jpg',
   'first_air_date': '2005-02-21',
   'name': 'Avatar: The Last Airbender',
   'vote_average': 8.737,
   'vote_count': 4218},
  {'adult': False,
   'backdrop_path': '/lJuQBW4w1x6NgD514xDPqZ2Lbpz.jpg',
   'genre_ids': [16, 18, 9648],
   'id': 220542,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '薬屋のひとりごと',
   'overview': "Maomao lived a peaceful life with her apothecary father. Until one day, she's sold as a lowly servant to the emperor's palace. But she wasn't meant for a compliant life among royalty. So when imperial heirs fall ill, she decides to step in and find a cure! This catches the eye of Jinshi, a handsome palace official who promotes her. Now, she's making a name for herself solving medical mysteries!",
   'popularity': 332.536,
   'poster_path': '/e3ojpANrFnmJCyeBNTinYwyBCIN.jpg',
   'first_air_date': '2023-10-22',
   'name': 'The Apothecary Diaries',
   'vote_average': 8.7,
   'vote_count': 235},
  {'adult': False,
   'backdrop_path': '/4Mt7WHox67uJ1yErwTBFcV8KWgG.jpg',
   'genre_ids': [10759, 35, 16],
   'id': 37854,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': 'ワンピース',
   'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
   'popularity': 178.138,
   'poster_path': '/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg',
   'first_air_date': '1999-10-20',
   'name': 'One Piece',
   'vote_average': 8.7,
   'vote_count': 4774},
  {'adult': False,
   'backdrop_path': '/jmV6NIzZxGzRoljFPwao6sh4Nny.jpg',
   'genre_ids': [18, 35],
   'id': 259666,
   'origin_country': ['MX'],
   'original_language': 'es',
   'original_name': 'Nadie nos va a extrañar',
   'overview': "It's the '90s, and five losers run an illegal business at their high school. They sell homework and assignments to their classmates. The advantage is that no one ever suspects the nerds. Their business brings them money and popularity. But hormones and an unexpected death threaten to ruin everything. If the business collapses, their futures and their friendships are at risk.",
   'popularity': 47.881,
   'poster_path': '/py0s87C9214KRbZ4kWLQfgsE9ET.jpg',
   'first_air_date': '2024-08-09',
   'name': 'No One Will Miss Us',
   'vote_average': 8.719,
   'vote_count': 208},
  {'adult': False,
   'backdrop_path': '/A6tMQAo6t6eRFCPhsrShmxZLqFB.jpg',
   'genre_ids': [10759, 16, 10765, 35],
   'id': 31911,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
   'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
   'popularity': 84.29,
   'poster_path': '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
   'first_air_date': '2009-04-05',
   'name': 'Fullmetal Alchemist: Brotherhood',
   'vote_average': 8.69,
   'vote_count': 2117},
  {'adult': False,
   'backdrop_path': '/uGy4DCmM33I7l86W7iCskNkvmLD.jpg',
   'genre_ids': [16, 35, 10765, 10759],
   'id': 60625,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Rick and Morty',
   'overview': "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
   'popularity': 408.777,
   'poster_path': '/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg',
   'first_air_date': '2013-12-02',
   'name': 'Rick and Morty',
   'vote_average': 8.692,
   'vote_count': 9930},
  {'adult': False,
   'backdrop_path': '/t15KHp3iNfHVQBNIaqUGW12xQA4.jpg',
   'genre_ids': [80, 18],
   'id': 60059,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Better Call Saul',
   'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
   'popularity': 247.772,
   'poster_path': '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg',
   'first_air_date': '2015-02-08',
   'name': 'Better Call Saul',
   'vote_average': 8.7,
   'vote_count': 5409},
  {'adult': False,
   'backdrop_path': '/20eIP9o5ebArmu2HxJutaBjhLf4.jpg',
   'genre_ids': [18],
   'id': 87108,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Chernobyl',
   'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
   'popularity': 176.875,
   'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
   'first_air_date': '2019-05-06',
   'name': 'Chernobyl',
   'vote_average': 8.682,
   'vote_count': 6553},
  {'adult': False,
   'backdrop_path': '/ywQtHG17LZhAFZyZtBflhtFMtJ7.jpg',
   'genre_ids': [18, 10751],
   'id': 70785,
   'origin_country': ['CA'],
   'original_language': 'en',
   'original_name': 'Anne with an E',
   'overview': 'A coming-of-age story about an outsider who, against all odds and numerous challenges, fights for love and acceptance and for her place in the world. The series centers on a young orphaned girl in the late 1890’s, who, after an abusive childhood spent in orphanages and the homes of strangers, is mistakenly sent to live with an elderly woman and her aging brother. Over time, 13-year-old Anne will transform their lives and eventually the small town in which they live with her unique spirit, fierce intellect and brilliant imagination.',
   'popularity': 102.907,
   'poster_path': '/6P6tXhjT5tK3qOXzxF9OMLlG7iz.jpg',
   'first_air_date': '2017-03-19',
   'name': 'Anne with an E',
   'vote_average': 8.665,
   'vote_count': 4693},
  {'adult': False,
   'backdrop_path': '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
   'genre_ids': [16, 10765, 10759],
   'id': 1429,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '進撃の巨人',
   'overview': 'Many years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the heroic members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!',
   'popularity': 108.158,
   'poster_path': '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
   'first_air_date': '2013-04-07',
   'name': 'Attack on Titan',
   'vote_average': 8.7,
   'vote_count': 6546},
  {'adult': False,
   'backdrop_path': '/2w8FaLwwJTWr6ExUMeVgT2Th5YT.jpg',
   'genre_ids': [16, 35, 18, 10759],
   'id': 42705,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': 'はじめの一歩',
   'overview': "Makunouchi Ippo is an ordinary high school student in Japan. Since he spends most of his time away from school helping his mother run the family business, he doesn't get to enjoy his younger years like most teenagers. Always a target for bullying at school (the family fishing business grants him a distinct odor), Ippo's life is one of hardship. One of these after-school bullying sessions turns Ippo's life around for the better, as he is saved by a boxer named Takamura. He decides to follow in Takamura's footsteps and train to become a boxer, giving his life direction and purpose. Ippo's path to perfecting his pugilistic prowess is just beginning...",
   'popularity': 225.833,
   'poster_path': '/1LApB9C9kEkh2ZU2vzAhurNDipl.jpg',
   'first_air_date': '2000-10-03',
   'name': 'Fighting Spirit',
   'vote_average': 8.7,
   'vote_count': 1092},
  {'adult': False,
   'backdrop_path': '/1nfIEJu02Zhv9omTKkzwHnK8Dji.jpg',
   'genre_ids': [99, 10751],
   'id': 74313,
   'origin_country': ['GB'],
   'original_language': 'en',
   'original_name': 'Blue Planet II',
   'overview': 'There is nowhere more powerful and unforgiving yet more beautiful and compelling than the ocean. Join us and explore the greatest yet least known parts of our planet.',
   'popularity': 23.325,
   'poster_path': '/j1NsoYYDYHnPkRr7Enqr8tlexgO.jpg',
   'first_air_date': '2017-10-29',
   'name': 'Blue Planet II',
   'vote_average': 8.7,
   'vote_count': 269},
  {'adult': False,
   'backdrop_path': '/mGHrUSt2uA5RaIheSmBfRnRHPS8.jpg',
   'genre_ids': [16, 10765, 18, 10759, 35, 10762],
   'id': 92685,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Owl House',
   'overview': "An animated fantasy-comedy series that follows Luz, a self-assured teenage girl who accidentally stumbles upon a portal to a magical world where she befriends a rebellious witch, Eda, and an adorably tiny warrior, King. Despite not having magical abilities, Luz pursues her dream of becoming a witch by serving as Eda's apprentice at the Owl House and ultimately finds a new family in an unlikely setting.",
   'popularity': 127.212,
   'poster_path': '/zqjSex7DZn7p4dU7mMktdJ8zQV5.jpg',
   'first_air_date': '2020-01-10',
   'name': 'The Owl House',
   'vote_average': 8.7,
   'vote_count': 1628},
  {'adult': False,
   'backdrop_path': '/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 85937,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '鬼滅の刃',
   'overview': 'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.',
   'popularity': 78.681,
   'poster_path': '/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
   'first_air_date': '2019-04-06',
   'name': 'Demon Slayer: Kimetsu no Yaiba',
   'vote_average': 8.652,
   'vote_count': 6552}],
 'total_pages': 107,
 'total_results': 2123}

In [8]:
pd.DataFrame(response.json()['results']).head()

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,name,vote_average,vote_count
0,False,/7BzmK4MWc0cj4hCxwWURt6TS6UR.jpg,"[16, 10765, 10759, 35]",131378,[US],en,Adventure Time: Fionna & Cake,Fionna and Cake – with the help of the former ...,35.818,/fi1b6U1kp73xheECzqwzMn8u3mX.jpg,2023-08-31,Adventure Time: Fionna & Cake,8.995,203
1,False,/gc8PfyTqzqltKPW3X0cIVUGmagz.jpg,"[18, 80]",1396,[US],en,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",737.144,/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg,2008-01-20,Breaking Bad,8.900,14963
2,False,/j67Wi1mzPxPVVybjmaIsvzsqFDH.jpg,"[16, 10759, 35, 10765]",240411,[JP],ja,ダンダダン,In a bet to prove whether ghosts or aliens exi...,189.932,/6qfZAOEUFIrbUH3JvePclx1nXzz.jpg,2024-10-04,Dan Da Dan,8.800,386
3,False,/tuCU2yVRM2iZxFkpqlPUyvd6tSu.jpg,"[16, 35, 10765]",94954,[US],en,Hazbin Hotel,In attempt to find a non-violent alternative f...,110.633,/rXojaQcxVUubPLSrFV8PD4xdjrs.jpg,2024-01-18,Hazbin Hotel,8.800,1214
4,False,/sYXLeu5usz6yEz0k00FYvtEdodD.jpg,"[16, 10765, 18, 10759]",94605,[US],en,Arcane,Amid the stark discord of twin cities Piltover...,260.242,/abf8tHznhSvl9BAElD2cQeRr7do.jpg,2021-11-06,Arcane,8.800,4846

In [11]:
df=pd.DataFrame(response.json()['results']).head()[['id','original_name','overview','popularity','vote_average','vote_count']]
df

,id,original_name,overview,popularity,vote_average,vote_count
0,131378,Adventure Time: Fionna & Cake,Fionna and Cake – with the help of the former ...,35.818,8.995,203
1,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",737.144,8.900,14963
2,240411,ダンダダン,In a bet to prove whether ghosts or aliens exi...,189.932,8.800,386
3,94954,Hazbin Hotel,In attempt to find a non-violent alternative f...,110.633,8.800,1214
4,94605,Arcane,Amid the stark discord of twin cities Piltover...,260.242,8.800,4846

In [13]:
df=pd.DataFrame(response.json()['results'])[['id','original_name','overview','popularity','vote_average','vote_count']]
df

,id,original_name,overview,popularity,vote_average,vote_count
0,131378,Adventure Time: Fionna & Cake,Fionna and Cake – with the help of the former ...,35.818,8.995,203
1,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",737.144,8.900,14963
2,240411,ダンダダン,In a bet to prove whether ghosts or aliens exi...,189.932,8.800,386
3,94954,Hazbin Hotel,In attempt to find a non-violent alternative f...,110.633,8.800,1214
4,94605,Arcane,Amid the stark discord of twin cities Piltover...,260.242,8.800,4846
5,209867,葬送のフリーレン,After the party of heroes defeated the Demon K...,160.004,8.776,378
6,246,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",73.219,8.737,4218
7,220542,薬屋のひとりごと,Maomao lived a peaceful life with her apotheca...,332.536,8.700,235
8,37854,ワンピース,"Years ago, the fearsome Pirate King, Gol D. Ro...",178.138,8.700,4774
9,259666,Nadie nos va a extrañar,"It's the '90s, and five losers run an illegal ...",47.881,8.719,208
10,31911,鋼の錬金術師 FULLMETAL ALCHEMIST,Disregard for alchemy’s laws ripped half of Ed...,84.290,8.690,2117
11,60625,Rick and Morty,Rick is a mentally-unbalanced but scientifical...,408.777,8.692,9930
12,60059,Better Call Saul,Six years before Saul Goodman meets Walter Whi...,247.772,8.700,5409
13,87108,Chernobyl,The true story of one of the worst man-made ca...,176.875,8.682,6553
14,70785,Anne with an E,"A coming-of-age story about an outsider who, a...",102.907,8.665,4693
15,1429,進撃の巨人,"Many years ago, the last remnants of humanity ...",108.158,8.700,6546
16,42705,はじめの一歩,Makunouchi Ippo is an ordinary high school stu...,225.833,8.700,1092
17,74313,Blue Planet II,There is nowhere more powerful and unforgiving...,23.325,8.700,269
18,92685,The Owl House,An animated fantasy-comedy series that follows...,127.212,8.700,1628
19,85937,鬼滅の刃,"It is the Taisho Period in Japan. Tanjiro, a k...",78.681,8.652,6552

In [12]:
df=pd.DataFrame()

In [15]:
for i in range(1,429):
    response=requests.get('https://api.themoviedb.org/3/tv/top_rated?api_key=7ff9928e01325480ca86fddb66fa93d7')
    temp_df=pd.DataFrame(response.json()['results'])[['id','original_name','overview','popularity','vote_average','vote_count']]
    df=df[temp_df]

ValueError: Boolean array expected for the condition, not int64